MAX_TITLE = 255
MIN_TITLE = 4

TEXTFIELD_WIDTH = 50
TEXTAREA_COLS = 100
TEXTAREA_ROWS = 15

FORMAT_BIGDATE = "%a, %d %b %Y"
FORMAT_DATE = "%m/%d/%y"
REG_PARSE_DATE = /^\d{4}-\d{2}-\d{2}$/

HTTP_STATUS_GOOD = 200
HTTP_STATUS_USERERROR = 406
HTTP_STATUS_FORBIDDEN = 403

APP_NAME = "TinySIS"
APP_DOMAIN = "nova.tinysis.org"
APP_ORGANIZATION_SHORTNAME = "Nova"
APP_ORGANIZATION = "The Nova Project"
APP_ACCOUNT_EMAIL = "admin@nova.tinysis.org"
APP_EXCEPTION_EMAIL = "bugs@baddabigboom.com"
APP_ORGANIZATION_HOMEROOM_NAME = "COOR"

FTE_HOURS = 25