MAX_TITLE = 255
MIN_TITLE = 4

TEXTFIELD_WIDTH = 50
TEXTAREA_COLS = 100
TEXTAREA_ROWS = 15

FORMAT_BIGDATE = "%a, %d %b %Y"
FORMAT_DATE = "%m/%d/%y"
REG_PARSE_DATE = /^\d{4}-\d{2}-\d{2}$/

HTTP_STATUS_GOOD = 200
HTTP_STATUS_USERERROR = 406
HTTP_STATUS_FORBIDDEN = 403

