javascripts:
  system:
    - external/prototype.js
    - external/effects.js
    - external/dragdrop.js
    - external/controls.js
    
    - external/jquery-1.6.2.min.js
    - external/jquery-ui.js
    - external/jquery_compat.js
    
    - external/underscore-min.js

    - external/modalbox.js
  tinysis:
    - application.js
    - tiny.js
    - credits.js
    - behaviors.js
    - behaviors/*.js
  assignments:
    - assignments.js
    
