javascripts:
  system:
    - public/javascripts/external/prototype.js
    - public/javascripts/external/effects.js
    - public/javascripts/external/dragdrop.js
    - public/javascripts/external/controls.js
    - public/javascripts/external/jquery-1.6.2.min.js
    - public/javascripts/external/jquery-ui.js
    - public/javascripts/external/jquery_compat.js
    - public/javascripts/external/underscore-min.js
    - public/javascripts/external/modalbox.js

  tinysis:
    - public/javascripts/application.js
    - public/javascripts/tiny.js
    - public/javascripts/credits.js
    - public/javascripts/behaviors.js
    - public/javascripts/behaviors/*.js

  assignments:
    - public/javascripts/assignments.js
    
