javascripts:
  system:
    - javascripts/external/prototype.js
    - javascripts/external/effects.js
    - javascripts/external/dragdrop.js
    - javascripts/external/controls.js
    - javascripts/external/jquery-1.6.2.min.js
    - javascripts/external/jquery-ui.js
    - javascripts/external/jquery_compat.js
    - javascripts/external/underscore-min.js
    - javascripts/external/modalbox.js

  tinysis:
    - javascripts/application.js
    - javascripts/tiny.js
    - javascripts/credits.js
    - javascripts/behaviors.js
    - javascripts/behaviors/*.js

  assignments:
    - javascripts/assignments.js
    
