javascripts:
  system:
    - prototype.js
    - effects.js
    - dragdrop.js
    - controls.js
    
    - jquery/jquery-1.4.3.min.js
    - jquery/jquery-ui.js
    - jquery/jquery_compat.js
    - jquery/jquery.livequery.js
    
    - modalbox.js
  tinysis:
    - application.js
    - tiny.js
    - credits.js
    - behaviors/notes.js
    - behaviors/filterform.js
  assignments:
    - assignments.js
    